### ISSUE TITLE
Fails to Deserialize 

### ISSUE THREAD

**Issue by ghost** [TGMDevelopment/JsonTGM#6]
```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at xyz.matthewtgm.json.serialization.JsonDeserializer.createClassInstance(JsonDeserializer.java:68)
	at xyz.matthewtgm.json.serialization.JsonDeserializer.deserialize(JsonDeserializer.java:31)
	at dev.fxe.TGMJsonBenchmark.deserialize(TGMJsonBenchmark.java:19)
	at dev.fxe.DataGenerator.main(DataGenerator.java:39)
```
```java

public static void deserialize() throws FileNotFoundException {
	BufferedReader bufferedReader = new BufferedReader(new FileReader("people.json"));
	String data = bufferedReader.lines().collect(Collectors.joining());
	Person[] people = JsonDeserializer.deserialize(data, Person[].class);
}


public class Person {

	String fullName;
	String firstName;
	String lastName;
	String address;
	int age;
	Book favouriteBook;

	public Person(String fullName, String firstName, String lastName, String address, int age, String author, String title) {
		this.fullName = fullName;
		this.firstName = firstName;
		this.lastName = lastName;
		this.address = address;
		this.age = age;
		this.favouriteBook = new Book(author, title);
	}
}

public class Book {

	String author;
	String title;

	public Book(String author, String tittle) {
		this.author = author;
		this.title = tittle;
	}
}
```

The file to deserialize 

[people.json](https://gist.github.com/1fxe/df89207a702ed2dd9fb7d900ace7b6da)

**Comment by Deftu** [comment]
Use the `JsonReader`, and your class needs to have an empty constructor for it to work atm.

**Comment by Deftu** [comment]
It appears I forgot to make inner-class serialization and deserialization. I'll make it when possible.
